### ISSUE TITLE
[homepage template] Primary and Header theme menu locations

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#1]
Create the menu locations so we can assign menus to them. 

There are five menu areas on the homepage. Two in the header, one the main body and two in the footer (quick links and privacy/terms of use)

**Comment by bdolor** [comment]
In order to complete #2 I created a few menus...and paid little attn to styling.

**Comment by alex-418** [comment]
@ehbeattie Can you confirm if we axed the 2-column section with the links on the homepage??
his would require a menu, so just wanted to make sure what the decision was before proceeding. 

![screenie](https://user-images.githubusercontent.com/17072191/52246141-864fe100-2899-11e9-97cc-18b8b33b9055.png)

**Comment by dshaykewich** [comment]
@ehbeattie , per stand-up discussion this morning (and recollection of the previous discussion), this section will be removed.

**Comment by alex-418** [comment]
Thanks @dshaykewich for capturing that decision here. I've now created the menus on helga (with sample pages) to reflect the design.

**Comment by ehbeattie** [comment]
If you mean this part, yes, please deep six it. 
<img width="470" alt="screen shot 2019-02-05 at 10 38 50 am" src="https://user-images.githubusercontent.com/44707412/52296060-4ab52580-2932-11e9-83f4-43e0be3896bd.png">
