### ISSUE TITLE
Homepage: "Getting Started" section component styling

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#10]
No carousel, unless there's time. 

In API they are in Support Resources -> Guides and Toolkits. 

- Limit to 4 (desc order, most recent by modified date)
- Choose which ones to display at random
- Clicking on cover takes you to that guide/toolkit
- The browse all button takes you to https://open.bccampus.ca/find-open-textbooks/?subject=Support%20Resources

**Comment by bdolor** [comment]
![image](https://user-images.githubusercontent.com/2048170/50715704-52339700-1033-11e9-959b-fcc1cdd66e22.png)

**Comment by alex-418** [comment]
![random_number](https://user-images.githubusercontent.com/17072191/51858422-8a07c480-22e9-11e9-9e98-d5263f0c1a0d.png)
