### ISSUE TITLE
Find Open Textbooks Page: Search box 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#11]
Create a search box with the same filters as the Homepage search, but the styling differs: 

Keyword (api: keyword)
Title(not clear if we can get from api)
Author(api: contributor)
Subject (api: subject)

**Comment by bdolor** [comment]
similar to https://github.com/BCcampus/open-sage/issues/6

Pending further investigation it is the case that searching by subject area needs to be an exact string match and searching by title only is not possible.

Requires more investigation into the limitations of the search api provided at http://solr.bccampus.ca:8001/bcc/apidocs.do

**Comment by alex-418** [comment]
Can be seen here:
https://helga.bccampus.ca/wp/opentextbooks/open-textbooks/

**Comment by alex-418** [comment]
@ehbeattie would like to suggest changing the searchbox text to just "search". 

Here is how it currently looks on mobile:
![long-search-text](https://user-images.githubusercontent.com/17072191/52505512-8ead6200-2ba0-11e9-8d68-1b54dba71626.png)


And here's what it would look like with the change:
![search](https://user-images.githubusercontent.com/17072191/52505524-9cfb7e00-2ba0-11e9-8e49-6e1a080c18bd.png)

**Comment by ehbeattie** [comment]
@alex-418 - I approve of the suggestion.

**Comment by alex-418** [comment]
@ehbeattie Thank you, i've made the change. Good to go!

**Comment by alex-418** [comment]
Will update as discussed the contents of the search input box to match the search box in the header.
