### ISSUE TITLE
[70.3] Customizer section for hero and PB callout

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#113]
Create a section in the customizer for this page, to allow setting the pages which have the featured image and excerpt for:

1.) The hero image 
2.) "Creating open textbooks with PressBooks" page

**Comment by ehbeattie** [comment]
Is there a page to view for this one?

**Comment by alex-418** [comment]
https://helga.bccampus.ca/wp/opentextbooks/create-open-textbooks/ 

You can switch out the default page in these sections in the customizers "Create Open Textbooks" section.

**Comment by ehbeattie** [comment]
Oh, hey, cool. I've added some copy and images to play around. I notice that the title appears twice here, which is odd: https://helga.bccampus.ca/wp/opentextbooks/create-open-textbook

**Comment by alex-418** [comment]
@ehbeattie The duplicate title is because that's the page title of the one set in the customizer... as per design in https://github.com/BCcampus/open-sage/issues/70 it shows the title of the page, and then the title of that hero section. Assigning a different page will change that second title.... I've implemented the blue background styling via https://github.com/BCcampus/open-sage/commit/0770b1ef200746f72f8000d66e7b7edcc1288360 to make that more obvious. (please note, clearing browser cache may be required) 

![blue_bg](https://user-images.githubusercontent.com/17072191/54242213-04c72080-44e1-11e9-9666-fd49cf1dd318.png)

**Comment by alex-418** [comment]
I've captured the height difference issue between the two in https://github.com/BCcampus/open-sage/issues/120

**Comment by ehbeattie** [comment]
The title of the hero section should be 'Getting started" but I'm unsure where to change that. Maybe I should wait until my coffee has set in...

Change from this: <img width="366" alt="Screen Shot 2019-03-13 at 6 31 02 AM" src="https://user-images.githubusercontent.com/44707412/54282650-aee28f00-4559-11e9-9818-88da4c8f3c63.png">

To this: <img width="219" alt="Screen Shot 2019-03-13 at 6 31 55 AM" src="https://user-images.githubusercontent.com/44707412/54282669-b86bf700-4559-11e9-9e5a-680fa387500b.png">

**Comment by bdolor** [comment]
above Alex notes: 
> Assigning a different page will change that second title

you would perform that action in the customizer

**Comment by ehbeattie** [comment]
The page assigned it correct, but changing the page title didn't change the hero header title. #usererror

**Comment by bdolor** [comment]
Here's a screen shot:

![image](https://user-images.githubusercontent.com/2048170/54291084-4d2a2100-4569-11e9-83cf-0241aa03eab5.png)
