### ISSUE TITLE
[78.6] Fix <figcaption> and match the design as closely as possible 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#117]
Match design where possible, and make figcaptions play nicely. The major difference is that we kept with the sidebar on the right, while the design uses that space for the "get this book" component.

1. Fix <figcaptions> by either shortening, moving, or removing them while maintaining the required attribution. 
![figcaps](https://user-images.githubusercontent.com/17072191/54224572-07ad1b80-44b7-11e9-81c2-4553df626694.png)

2. Match Location and styling of meta (such as posted and author information) 

3. Move the "get this book" component to below the cover image, so user doesn't have to scroll down like in the design. 

![book](https://user-images.githubusercontent.com/17072191/54316689-9d6fa600-459e-11e9-9802-e2b183cc8b13.png)

**Comment by ehbeattie** [comment]
Excellent work on this one.
