### ISSUE TITLE
[76.3] Default cover image

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#118]
Books without a default image show up as a white box (see screenshot).
![no-image](https://user-images.githubusercontent.com/17072191/54225498-0a107500-44b9-11e9-8e05-998081016ae7.png)

 @ehbeattie can you please provide a generic image for book covers? Something similar to this:
![placeholder-coverphoto](https://user-images.githubusercontent.com/17072191/54225599-4ba12000-44b9-11e9-9f67-63b736f457c3.jpg)

**Comment by ehbeattie** [comment]
I had supplied one in a previous thread, but I can't seem to find it. @bdolor - any insight?

**Comment by ehbeattie** [comment]
Does this work?

![textbook-cover (1)](https://user-images.githubusercontent.com/44707412/54316377-cb081f80-459d-11e9-8d5c-e7fbccba0b77.jpg)

**Comment by alex-418** [comment]
@ehbeattie after some investigation discovered that the missing cover image for "open pedagogy resources" is actually a setting in Equella when editing the resource: 
 
![equella](https://user-images.githubusercontent.com/17072191/54392957-2867a380-4666-11e9-8a98-e609566e594c.png)

Although I have added  the default cover image you provided to our theme via 4847f28, this will not show up yet as this new image does not exist on production. 

Perhaps @josieg or whoever is doing content for launch can update the link for the cover image in Equella once it's live. The link will be as follows: 
http://open.test/app/themes/open-sage/dist/images/default-cover.jpg

**Comment by ehbeattie** [comment]
Can we leave this in the backlog as a non-dev task so it doesn't fall off my radar for launch day?

**Comment by alex-418** [comment]
fyi @ehbeattie moved this one to sprint backlog
