### ISSUE TITLE
Find Open Textbooks Page: Getting Started section component styling

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#12]
Display the 3 most recently added **books** as per design:
Link to "suggest a book" goes to: https://open.bccampus.ca/suggestion-for-the-collection/
Link to "browse our collection" goes to: https://open.bccampus.ca/find-open-textbooks/

**Comment by bdolor** [comment]
This feature would best be served by integrating with opentextbooks application

![image](https://user-images.githubusercontent.com/2048170/50716761-f8819b80-1037-11e9-8f2e-71523980d5dc.png)

**Comment by ehbeattie** [comment]
Content for this one: Choose a guide to start finding, creating, modifying, and sharing open educational resources

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/open-sage/pull/99 can be validated at https://helga.bccampus.ca/wp/opentextbooks/open-textbooks-2/

**Comment by ehbeattie** [comment]
Sweeeeeet.
