### ISSUE TITLE
[70.5] Hero section max-height and styling

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#120]
Hero section expands based on the excerpt length, making the left side a lot longer than the right, cuasing this issue(see screenshot). Consider giving it a max height and trim the excerpt length. 

![hero](https://user-images.githubusercontent.com/17072191/54242486-09400900-44e2-11e9-8d4c-b2eec88c523d.png)

**Comment by alex-418** [comment]
issue also affects cards, fixing those as well (see screenshot) 
<img width="917" alt="cards" src="https://user-images.githubusercontent.com/17072191/54453048-b8aff200-4713-11e9-913c-d9b0ca04f8cf.png">

**Comment by alex-418** [comment]
Hero image will always be a fixed height, limit excerpt text and cards to match that height

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/open-sage/pull/131

This fixes the height issues with the hero image on the homepage, and hero/triple cards in "use open textbooks page". Also applies to the hero image in "create open textbooks page". 
This trims the excerpt lengths to 40 words (this is closest match to design possible, without having to do this individually for each hero section and card)

**Comment by alex-418** [comment]
@ehbeattie Please note that Github automatically closes an issue if it detects some keywords such as "completed" in the text... it's handy, but can be confusing as it's not validated yet. We can re-open these in the case where there's more work.

**Comment by ehbeattie** [comment]
How shall I proceed?

**Comment by alex-418** [comment]
If you're happy with the 40 word count and how the hero and card sections look in the 3 pages I noted above, then please move to validate.

**Comment by ehbeattie** [comment]
How many characters are allowed on BCcampus? I would like to match what we have implemented there.

**Comment by alex-418** [comment]
The design differs slightly, for example there's no excerpt in the BCcampus hero images, but for the others cards yes it's the same excerpt length.

**Comment by ehbeattie** [comment]
Ok, sounds good.
