### ISSUE TITLE
Homepage: Add section with quote and image

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#125]
1. 2-card design (no menu)
2. Add to customizer "Homepage" section 
3. Create partial, add to homepage template 

![Screen Shot 2019-03-18 at 9 32 44 AM](https://user-images.githubusercontent.com/17072191/54546422-dc1bac80-4960-11e9-8e28-5e8fe3b02ad6.png)

**Comment by alex-418** [comment]
Completed via #132. It adds a customizer settings to homepage section (see screenshot). It will use the excerpt and featured image that is set there. 

![customizer](https://user-images.githubusercontent.com/17072191/54564987-662c3b00-498a-11e9-8f8a-ba69867355e9.png)

![quote](https://user-images.githubusercontent.com/17072191/54565011-6fb5a300-498a-11e9-9888-bcd6431f77dc.png)

**Comment by alex-418** [comment]
Removed page title and learn more link from the homepage quote section, changed text color to match design, and made text responsive via https://github.com/BCcampus/open-sage/commit/ce12884797d0efee4239eecaae89fc2f3370c82a

**Comment by ehbeattie** [comment]
Can you enlarge the font to match the mockup a little more?

**Comment by alex-418** [comment]
Updated font size and gave the tablet and mobile some love (screenies below) to ensure this works well on all devices via https://github.com/BCcampus/open-sage/commit/500ddaeefc6cb85a330a50b89a0a939f9d53953a  

Desktop:
![desktop](https://user-images.githubusercontent.com/17072191/54704142-6e55b900-4af7-11e9-94b3-bd447f6fb6bb.png)

iPad: 
![Ipad](https://user-images.githubusercontent.com/17072191/54704155-73b30380-4af7-11e9-9bdd-513eef6edaf0.png)

iPhone: 
![iphone](https://user-images.githubusercontent.com/17072191/54704172-7b72a800-4af7-11e9-9c47-c8bd9483d4f9.png)

**Comment by ehbeattie** [comment]
This looks great, thanks, Alex!
