### ISSUE TITLE
Homepage: Stats text

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#126]
Text:
At BCcampus, we recognize and embrace the value of open technologies, actively facilitating, evaluating, and creating open educational resources to share with system partners and stakeholders across the province and around the world. 
Millions of student-dollars in B.C. have been saved through hundreds of open textbooks adopted in thousands of classrooms:

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/open-sage/commit/396c9824266bf6da3ffd4c36b06f325c3f7dd9f6

I felt the text might be a bit too long? Especially on mobile. Made the font a bit smaller, let me know if you want any changes. 

![stats](https://user-images.githubusercontent.com/17072191/54559396-332f7a80-497d-11e9-89c5-0058cfb1c29a.png)

**Comment by ehbeattie** [comment]
I'll condense the copy. Please standby.

**Comment by ehbeattie** [comment]
Updated... 

At BCcampus, we’re using open technologies to facilitate, evaluate, and create open educational resources to share across the province and around the world, resulting in hundreds of open textbooks adopted in thousands of classrooms and saving millions of student-dollars:

**Comment by alex-418** [comment]
Text has been updated via https://github.com/BCcampus/open-sage/commit/7c8efcb4e65d402387a8da5b0eaca97b333e2c8f will show up on helga in a few minutes.

**Comment by ehbeattie** [comment]
Can you try right aligning the text?

**Comment by alex-418** [comment]
**Here's right aligned:** 
![right](https://user-images.githubusercontent.com/17072191/54644527-b96bbf80-4a56-11e9-8ce4-1000a47075fe.png)

**Here's left aligned:** 
![left](https://user-images.githubusercontent.com/17072191/54644549-cd172600-4a56-11e9-8b1d-9cf6cccd4992.png)

**Here's if it was a single line, keeping text centered:** 
![single_center](https://user-images.githubusercontent.com/17072191/54644555-d1dbda00-4a56-11e9-8eae-bcecdd466c56.png)


Let me know which one you'd like to go with.

**Comment by ehbeattie** [comment]
Can you enlarge the font? My old lady eyes can't see this tiny writing. I'm trying to match the mockup as best as possible here.

**Comment by alex-418** [comment]
If you click on the picture it should enlarge to actual size

**Comment by alex-418** [comment]
Completed as discussed in stand-up (Left aligned text, normal font size) via https://github.com/BCcampus/open-sage/commit/521353dc86c46123ad4e10d072e191591db1c910 will be on Helga in a few minutes (screenshot below):

![left-align](https://user-images.githubusercontent.com/17072191/54701274-ea4d0280-4af1-11e9-8d32-6a6391a11716.png)

**Comment by ehbeattie** [comment]
Looks great!
