### ISSUE TITLE
Missing heading on single book details "Adoptions" 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#135]
The configuration file that controls these headings is not version controlled, therefore it got missed. Ensure the "Adoptions" heading exists on cert and prod. 

<img width="411" alt="Screen Shot 2019-03-19 at 1 05 55 PM" src="https://user-images.githubusercontent.com/17072191/54665641-e1820f80-4aa4-11e9-8a59-07c30593873a.png">

**Comment by alex-418** [comment]
This has been completed on both Helga(cert) and Production. You can confirm and validate by visiting an individual book and see the "Adoptions" heading now appears. 

This is what the config file looks like in case anyone is curious: 
![config](https://user-images.githubusercontent.com/17072191/54666999-8a7e3980-4aa8-11e9-8153-773d340b4ae2.png)

**Comment by ehbeattie** [comment]
Awesome!
