### ISSUE TITLE
Single book page: Update text and move authors to own line 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#136]
1. On the individual textbook pages, change the wording from published to posted and keep updated as is. (approved by OpenEd) 

2. Move the author details down a line to give more space

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/opentextbooks/commit/5a5ac8ee46125e3872a2bbac70d9d070a69c2747 and can be validate on a single book page on helga/cert.

**Comment by ehbeattie** [comment]
Much better.
