### ISSUE TITLE
Toolkits component: Remove "Faculty" from title 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#137]
Remove "Faculty" (see screenshot) 
<img width="691" alt="Screen Shot 2019-03-19 at 2 00 43 PM" src="https://user-images.githubusercontent.com/17072191/54665934-b350ff80-4aa5-11e9-845f-2cbcf9039d79.png">

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/open-sage/commit/207ba2a6fecc9a0233337a1ef0398dd82d545d19

**Comment by ehbeattie** [comment]
Perfect.
