### ISSUE TITLE
Stats page: Tab headings and blurbs 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#138]
1. Change open.bccampus.ca stats to Collection and add the following blurb on the page: This page contains download and access stats from the last four months for all books in the B.C. Open Textbook Collection. 

2. Change the opentextbc.ca stats to Pressbooks and add the following blurb: This page lists usage and downloads stats for books in the BCcampus (opentextbc.ca) Pressbooks. The downloads stats only include files downloaded from the webbook home page.

**Comment by ehbeattie** [comment]
The font size seems off here: 

<img width="954" alt="Screen Shot 2019-03-21 at 1 36 34 PM" src="https://user-images.githubusercontent.com/44707412/54783357-66247900-4bde-11e9-81d6-63ae0e656981.png">

**Comment by ehbeattie** [comment]
Can you change all but "summary" to paragraph styling?

**Comment by alex-418** [comment]
Sure thing. Any other changes you'd like to see on page? If yes, then would like suggest we capture those in a new issue.

**Comment by ehbeattie** [comment]
That is all I see at the moment.

**Comment by alex-418** [comment]
@ehbeattie Went through each tab, applied the same paragraph styling to all of them instead of the `<h4>` and `<h3>` headings they had.
