### ISSUE TITLE
Homepage A11y: Social media icons alt tags do not need "icon"

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#147]
**Describe the bug**
The alt tags for social media icons do not need the word "icon"

**To Reproduce**
https://helga.bccampus.ca/wp/opentextbooks/

**Expected behavior**
No "icon" in alt tag of social media icons.

**Screenshots**
![icons](https://user-images.githubusercontent.com/23706762/54765805-63625d80-4bb7-11e9-8d87-2e510f226e9e.jpg)

**Comment by alex-418** [comment]
completed via https://github.com/BCcampus/open-sage/commit/02c139a48efa53d9e1f0645681e468ae3abb310c
