### ISSUE TITLE
Homepage A11y: aria label on search bar

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#148]
**Describe the bug**
The aria-label on the search bar for the collection isn't clear. Currently, it says "Search terms."

**To Reproduce**
https://helga.bccampus.ca/wp/opentextbooks/

**Expected behavior**
I expect the aria label to say "Search open textbook collection" or "Search collection"

**Screenshots**
![aria](https://user-images.githubusercontent.com/23706762/54766992-8b52c080-4bb9-11e9-85b6-7cfe15ba37e6.jpg)

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/open-sage/commit/02c139a48efa53d9e1f0645681e468ae3abb310c
