### ISSUE TITLE
Stats Page: Collection Tab links to books not working 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#150]
**Describe the bug**
Clicking on a book title link takes you to a "not found" page 

**To Reproduce**
1. Go to https://helga.bccampus.ca/wp/opentextbooks/open-textbook-stats/
2. Click on "Collection" tab
3. Click on any book title link
4. Takes you to a "Not found" page

**Expected behavior**
Clicking on the link should take you to the books page

**Screenshots**
![not found](https://user-images.githubusercontent.com/17072191/54845831-a98eee00-4c97-11e9-8b4d-f1edfdbde0c5.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: All browsers

**Additional context**
URL is missing `?uuid` parameter.

**Comment by alex-418** [comment]
Fixed via https://github.com/BCcampus/open-sage/commit/9f24e6aea7853d55a063b8cc9f52349bd617f611 the book links now work as expected.

**Comment by ehbeattie** [comment]
Groovy, thanks, Alex.
