### ISSUE TITLE
Projects & Grants Page: Hero image + learn more button styling

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#153]
1. Add a hero image to the template 
2. Style links with `primary-btn` styling

**Comment by alex-418** [comment]
Completed via #167

**Comment by alex-418** [comment]
https://helga.bccampus.ca/wp/opentextbooks/projects-and-grants/

**Comment by ehbeattie** [comment]
Can you show me an example of the buttons? I am not seeing them. The heroes look good.

**Comment by alex-418** [comment]
@ehbeattie Yes, the easiest way to get those buttons on links for content that lives in the content editor, is to click on the "Text" tab in the editor, and apply the button styling. I've done this now on Helga for this page.
 
This is what you add to links: `class="btn btn-primary"` (see screenshot).

![styling](https://user-images.githubusercontent.com/17072191/55092620-162b3380-5070-11e9-913b-66ea7969552a.png)

**Comment by ehbeattie** [comment]
This is perfect, thanks!
