### ISSUE TITLE
Remove mystery Contact fields on Contact form on PROD

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/open-sage#159]
**Describe the bug**
On the live Open site (PROD), we have replaced all the content on the "Contact" page with a new Contact Form 7 form using a shortcode. Even though there is no other HTML on the page, there is now an additional, "mystery" contact form showing up on the bottom of the page. 
https://open.bccampus.ca/contact/

Though this extra contact form looks nice, I don't know where the information is going to, and this second form is not needed on this page. 

**To Reproduce**
1. Go to https://open.bccampus.ca/contact/
2. Scroll down the page. 
3. There is a second "contact" form at the bottom of the page. 

**Expected behavior**
Only the Contact Form 7 "Contact" form shows on this page. The second contact form is removed.

**Screenshots**
<img width="383" alt="OpenEdContactForm-Mystery" src="https://user-images.githubusercontent.com/26391359/54937067-f9142a80-4ee0-11e9-9e6f-cce828f8f66e.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox, etc.
 - Version - all

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: OS version 12.1.4
 - Browser Firefox
 - Version 15.0

**Additional context**

This revised page will be used on the new Open site as well. We had to launch this page to the live site now because Custom Answers is no longer being used to accept feedback from users.

**Comment by alex-418** [comment]
This is a strange one... can't find what is generating this extra contact form. I suspected this could be the honeypot. However, when I disabled the honeypot plugin it had no effect... need more time to investigate what's causing this. 

![scooby](https://user-images.githubusercontent.com/17072191/54957483-24623e00-4f10-11e9-8728-3ae300333fbc.gif)

**Comment by paulagaube** [comment]
@alex-418 Jinkies! I wondered if the mystery form was linked to the page name "contact" but it also appeared on the Contact page "contact-2". I could try creating a new page with a different name with only the short code and see if that works or not.

**Comment by alex-418** [comment]
@paulagaube That would be great, let me know if that resolves it please.

**Comment by alex-418** [comment]
@paulagaube created a new contact form and the issue went away.

**Comment by paulagaube** [comment]
New contact form is here: https://open.bccampus.ca/contact-us/

We will relink old contact pages to this contact page instead today.
