### ISSUE TITLE
Find Open Textbooks: Other Collections section

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#16]
Give the user the ability to update of modify the text. (customizer option and menu that can be assigned for example)

**Comment by bdolor** [comment]
With menu as an option questions are: 
- can a truncated version of a menu be put on the template page?
- can a menu item be easily placed inside the wysiwg of a content page?

For the blurb above the links, there is a desire to have distinct content areas for both the template page and the content page.

**Comment by alex-418** [comment]
Switch the Other collections and MARC section to a 2-column cards with link to the page(just like on the homepage.)  The content is in https://github.com/BCcampus/open-sage/issues/30 add option in customizer to set the page ID to show for each card.

**Comment by alex-418** [comment]
@ehbeattie to provide images for the cards

**Comment by alex-418** [comment]
Will be ready for validation once https://github.com/BCcampus/open-sage/pull/98 is merged

**Comment by ehbeattie** [comment]
Do you have access to the images for these cards?

**Comment by alex-418** [comment]
@ehbeattie Since we switched this to a 2-column card layout, I added a new section in the customizer menu called "Find Open Textbooks" to give you guys full control of the content. So whatever pages you choose on there, it will use that pages featured image in the cards, along with the excerpt text that's entered.

**Comment by ehbeattie** [comment]
Perfect, thank you!
