### ISSUE TITLE
Right-side menu not display on mobile

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#160]
**Describe the bug**
When viewing on a mobile phone, the left side menu disappears. 

**To Reproduce**
1. Go to the "Find Open Textbooks" page or an individual book page on mobile
2. The right hand side menu doesn't appear

**Expected behavior**
The menu should be displayed.

**Comment by alex-418** [comment]
Narrowed down to a glitch from the browser testing tool. The right side menu is displaying as expected on mobile. 

![menu](https://user-images.githubusercontent.com/17072191/54947003-8b72f900-4ef6-11e9-9821-ffed13f73c4e.png)

**Comment by ehbeattie** [comment]
Hi,

I think this makes sense. Good to go! 

Cheers,

Erin
