### ISSUE TITLE
Move all menus to the left

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#162]
Decision captured in https://github.com/BCcampus/open-sage/issues/158 to improve accessibility, the tabbing order for keyboard navigation requires the menu element to come before the content.

**Comment by alex-418** [comment]
@ehbeattie Moved the following pages menus to the left via https://github.com/BCcampus/open-sage/commit/4a8148a9544c08896c645900e5ef9e386d594d6a let me know if I missed one! 

- Find/Browse open textbooks page 
- Individual book page 
- Generic (Default) page
- Stats page

**Comment by ehbeattie** [comment]
I've noticed that the child pages in the side nav looks a little odd <img width="303" alt="Screen Shot 2019-03-27 at 1 20 41 PM" src="https://user-images.githubusercontent.com/44707412/55109518-433d0d80-5093-11e9-9698-34fca24ee393.png">

**Comment by alex-418** [comment]
It looks a little odd because those are grandchildren. The menu itself consists of the child pages. The design didn't have any grandchildren, so that's why styling and functionality are a bit wonky. Can you please confirm the nesting order is correct? And if it is, maybe there's now a need for grandchildren to be on the menu as well? I'll see what I can do about styling, then we'll look at if the functionality works well (right now visiting the grandchild page lists other grandchildren of the parent)

**Comment by alex-418** [comment]
Discussed and the content will be restructured so the relationships are Parent and Child only.
