### ISSUE TITLE
Heading  design for new left menu pages

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#163]
Having moved all menus to the left in #162, we are now left with the following design for each of the following pages (see screenshots below). 
Issues to fix:

1. The page titles are in the wrong position, wrong, or duplicated in some pages

2. Position of the content needs line up/match new sidebar position 

### **Browse/Find open textbooks page:** 
![browse](https://user-images.githubusercontent.com/17072191/55017960-1c0d1000-4faf-11e9-9a0c-73ef667fd142.png)

### **Single book page:** 
![single](https://user-images.githubusercontent.com/17072191/55017975-23ccb480-4faf-11e9-9cee-57352a28b3af.png)

### Generic (default) page:
![generic](https://user-images.githubusercontent.com/17072191/55018011-37781b00-4faf-11e9-8b9b-011b806de1eb.png)

### **Stats Page:** 
Didn't need a sidebar but had one, removed it and made it full width via https://github.com/BCcampus/open-sage/commit/30b29117ba7d8f812232c3982a3b2b715e58301d

![stats](https://user-images.githubusercontent.com/17072191/55018220-93db3a80-4faf-11e9-8f5f-ece3488eec94.png)

**Comment by alex-418** [comment]
@ehbeattie any additional comments or input for these pages? I will do my best to make them look good and fix the 2 issues I identified. Will let you know when ready for review.

**Comment by alex-418** [comment]
@ehbeattie  Improvements for Browse/Find open textbooks page finished... how's this look? Any other changes you want to this page? (I haven't pushed to helga, tackling all of these together via #164 then pushing over) 
 
![new_browse](https://user-images.githubusercontent.com/17072191/55024442-17028d80-4fbc-11e9-8d30-70c05265fec3.png)

**Comment by alex-418** [comment]
@ehbeattie Here's the single page ... fixed the duplicated and wrong title: 

![single](https://user-images.githubusercontent.com/17072191/55025970-364eea00-4fbf-11e9-8fe8-59494b4c7bd6.png)

Same thing for generic/default pages: 
![generic](https://user-images.githubusercontent.com/17072191/55026024-59799980-4fbf-11e9-911d-5847c7b39eff.png)

**Comment by alex-418** [comment]
Merged via #164 these changes should be on helga for you to review soon. 
Created #165 a new issue for the wrong breadcrumbs on single book pages.

**Comment by ehbeattie** [comment]
Great work, Alex. It looks good.

**Comment by alex-418** [comment]
The generic landing page templates needs the double page title removed, and the same padding/margins as the others.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/open-sage/commit/0afa9c00c82a4897deeed6906f15bbf1442e5aeb the following page has the same treatment applied as others (no double page title, same spacing): https://helga.bccampus.ca/wp/opentextbooks/need-help/

**Comment by ehbeattie** [comment]
Is it possible to align the two headers more?

<img width="405" alt="Screen Shot 2019-03-27 at 1 15 39 PM" src="https://user-images.githubusercontent.com/44707412/55109191-7501a480-5092-11e9-8483-2da0a0dfaca6.png">

**Comment by alex-418** [comment]
The content is indented slightly.... just note that changing that would impact the other pages as well.

**Comment by ehbeattie** [comment]
Would that mess things up?

**Comment by alex-418** [comment]
Not at all... completed via 86a8dcd

**Comment by ehbeattie** [comment]
Awesome!
