### ISSUE TITLE
Wrong breadcrumbs on single book pages

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#165]
**Describe the bug**
The breadcrumb is wrong on a single book page, thinks it's on the Browse/Find open textbooks page

**To Reproduce**
1. Go to a single book page 
2. See the wrong breadcrumbs

**Expected behavior**
The breadcrumb on a single book page should be same as the title of the page

**Screenshots**
![bread](https://user-images.githubusercontent.com/17072191/55026397-284d9900-4fc0-11e9-8d52-5915bfba53d1.png)

**Comment by alex-418** [comment]
Update text to "book page"

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/open-sage/commit/9245b4360cb4a63550e1f10f1a535e8a603c7492 

![breadcrumbs](https://user-images.githubusercontent.com/17072191/55192588-0c81f880-5162-11e9-9746-a7d9a3ba801d.png)

**Comment by ehbeattie** [comment]
Perfect!
