### ISSUE TITLE
Pages need a mobile "child pages" menu 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#166]
Similar to #158 but for all pages that have child pages menu. 
Need to create the mobile version of this child pages menu. 

Example: https://helga.bccampus.ca/wp/opentextbooks/use-open-textbooks/

Right now the desktop menu disappears on this page, but no mobile menu is displayed at all.

**Comment by alex-418** [comment]
Completed via 86a8dcd
![Screen Shot 2019-03-27 at 5 44 15 PM](https://user-images.githubusercontent.com/17072191/55122154-0422b280-50bb-11e9-88da-b5bee41e5a3d.png)

**Comment by ehbeattie** [comment]
This looks good to me. :)
