### ISSUE TITLE
Download icons on files in collection all show as "website"

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#171]
**Describe the bug**
When looking at the list of files available under some book, the icons are all showing up as "Website" icons, even for PDF, Word, and EPUB files. The print icons are appearing as expected.

However, some books are fine. Such as [Health Case Studies](https://helga.bccampus.ca/wp/opentextbooks/2-0-find-open-textbooks/browse-our-collection/?uuid=de69ac1b-efb2-4575-941f-0e096fc738d6&contributor=&keyword=&subject=Health/Medical%20-%20General).

**To Reproduce**
1. Go to any book in the collection. (For example, [Word on College Reading and Writing](https://helga.bccampus.ca/wp/opentextbooks/find-open-textbooks/?uuid=7d69b4ad-9581-4788-b1c1-0ebe2ae8a97a&contributor=&keyword=&subject=))
2. Expand file options under "Editable" "Readable" and "Ancillary" files. 
3. Look at the icons. They all say "Website"

**Expected behavior**
I expect that the icons should match the file type that they are associated with.

**Screenshots**
![icons](https://user-images.githubusercontent.com/23706762/55111091-ce6bd280-5096-11e9-90cb-55978b7f35dc.jpg)

**Desktop (please complete the following information):**
 - Windows PC
 - Browser Firefox
 - Version 65.0.2

**Comment by alex-418** [comment]
@josieg this has to do with the work you did in https://github.com/BCcampus/opentextbooks/issues/152 and explains the inconsistencies with the icons being displayed. 

The way the icon was being generated can be seen in the screenshot below:
![icon_logic](https://user-images.githubusercontent.com/17072191/55177267-13980f00-5140-11e9-8e02-0e907125d17f.png)

So when you renamed "Digital PDF (.pdf)" and "Print PDF (.pdf)" it drops the .pdf which the icon generation logic was relying on... if that's the new logic, I can update this to search for "PDF" instead, and that should fix it for all uses cases. I'll let you know once it's done so you can verify.

**Comment by josieg** [comment]
Aww man. We removed .pdf .epub, .mobi .xml .html from file labels, so it's not just PDFs being affected. I didn't realize those labels were supporting that functionality.

**Comment by alex-418** [comment]
@josieg Just caught those too, will update them as well... then you can verify that they still all work as expected. 

And yea, really sucks this is the way it works lol, solution would be to add a field to equella with the correct filetypes, so that we could identify them that way.

**Comment by alex-418** [comment]
Changes made via https://github.com/BCcampus/opentextbooks/commit/6c90b68479ac60fa3caff3bc5098ec0bbe99ea7d give it a whirl in a few minutes to ensure these still work as expected.

**Comment by josieg** [comment]
Thanks @alex-418 !

The only one that still has a problem is the XML file that we have labelled "Pressbooks file." (See [editable files here](https://helga.bccampus.ca/wp/opentextbooks/find-open-textbooks/?uuid=6c4a9484-8d43-4a44-a565-09cc773aa53f&contributor=&keyword=&subject=History).) If I edit that file so that it says "Pressbooks XML file" instead, will that fix the problem? Or i can edit to "Pressbooks file (.xml)." Whatever is easiest.

**Comment by alex-418** [comment]
@josieg Sure, i've updated it via https://github.com/BCcampus/opentextbooks/commit/a5a6aa35036c6fc90efe5d01a7cca4ceb34424d1 so that it'll look for `XML` (not case sensitive, xml will work too)... so as along as that is somewhere in there, it'll add the correct icon.

**Comment by ehbeattie** [comment]
@josieg - is this all good?

**Comment by josieg** [comment]
I think so.
