### ISSUE TITLE
Individual book page A11Y: File icons in collection include full attribution information in the alt tag

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#172]
**Describe the bug**
All download file icons in the collection include full attribution information in the icon's alt tag.

For example, the alt tag for MOBI files is: MOBI file. This icon is licensed under a Creative Commons Attribution 3.0 License. Copyright Yusuke Kamiyamane."

This is confusing for screen-reader users and an incorrect place for icon attributions.

**To Reproduce**
1. Go to Health Case Studies.
2. Activate screen reader. (Or inspect element to view the alt tag)
3. Hear the screen reader read out full attribution info for each file download icon it finds.

**Expected behavior**
I expect that the alt tag would not include attribution or copyright information. We may need to find somewhere else for it.

**Comment by alex-418** [comment]
Spoke with @ehbeattie and we will remove this from alt tags

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/opentextbooks/commit/d78cea7bef416df6696233192dc5c6a1a4c48adf
