### ISSUE TITLE
Alert in header of current site

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#176]
Add an alert that shows up on the current site about the downtime. @ehbeattie to provide content.

**Comment by ehbeattie** [comment]
Alert: Please note this site will be down for maintenance on April 9, 2019, from 9am-12pm (Pacific).

**Comment by alex-418** [comment]
Thanks, i'm on it

**Comment by josieg** [comment]
Hi Alex, the "site down" notice is currently showing up on BCcampus.ca, but I think it should be showing on open.bccampus.ca

**Comment by alex-418** [comment]
@ehbeattie Completed, VPN is still down but I found an option in the theme settings to add HTML to the header. Let me know if it looks good to you. https://open.bccampus.ca/
