### ISSUE TITLE
"Terms" link in footer links to a "Sample page"

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#177]
**Describe the bug**
The "Terms" link in the footer links to a "sample" page rather than a "Terms" page.

**To Reproduce**
1. Go to the homepage https://helga.bccampus.ca/wp/opentextbooks/
2. Scroll to the bottom to find the black footer.
3. Click "Terms"
4. See that you are taken to a page called Sample Page (https://helga.bccampus.ca/wp/opentextbooks/sample-page/)

**Expected behavior**
I expect that this Terms link should take me to a Terms page. On bccampus.ca, there is a "Terms and Conditions" link that takes me to this page: https://bccampus.ca/terms-conditions/, but I don't know what should be done for Open.

**Comment by alex-418** [comment]
Completed and fixed on prod
