### ISSUE TITLE
Remove duplicate "Create Open Textbooks" page

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#178]
**Describe the bug**
There seems to be two "Create Open Textbooks" pages, so one of them needs to be removed.

**To Reproduce**
1. Go to the home page. 
2. Click "Create open textbooks" in the top menu. It takes you to https://helga.bccampus.ca/wp/opentextbooks/create-open-textbooks-2/
3. Go back to the home page.
4. Click "Learn more" under the "Create Open Textbooks" box. It takes you to https://helga.bccampus.ca/wp/opentextbooks/create-open-textbooks/

Note the difference in the URLS.

**Expected behavior**
I expect that there should only be one version of a page that is linked to. My guess would be that the link to keep is https://helga.bccampus.ca/wp/opentextbooks/create-open-textbooks/

**Comment by alex-418** [comment]
@josieg VPN is down, can't get to this right now. But it's all content, so we can just remove the duplicate page, and then update the menu so it links to the correct page. @ehbeattie knows how to do that, and I'd be glad to do this or help once the VPN is back up, let me know!

**Comment by josieg** [comment]
Woohoo I fixed it! Here is to figuring out the customizer and not breaking things!
