### ISSUE TITLE
Create Open Textbooks page: Error notice

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#179]
**Describe the bug**
There is an error notice showing up under "Useful resources" on the Create Open Textbooks page. 

In issue #178, I note a problem where there are two versions of this page. In one version of this page (See https://helga.bccampus.ca/wp/opentextbooks/create-open-textbooks/), there is also a web form showing below the error notice. Since there are no forms in the wireframe on this page, that web form should not be there. But maybe that's where the issue is coming from? 

**To Reproduce**
1. Go to Create Open Textbooks page (either https://helga.bccampus.ca/wp/opentextbooks/create-open-textbooks/ or https://helga.bccampus.ca/wp/opentextbooks/create-open-textbooks-2/), depending on what happens with issue #178 ).
2. Scroll to the "Useful resources" heading.
3. See the error notice.

**Expected behaviour**
There should be no error notice or web forms.

**Screenshots**
![errornotice](https://user-images.githubusercontent.com/23706762/55509680-60348c00-5611-11e9-8e4e-0271baa906bf.jpg)

**Desktop (please complete the following information):**
 - Windows
 - Browser: Firefox

**Comment by alex-418** [comment]
I'll mention @bdolor so he can chime in he feels this needs action, but as I understand it this won't be a problem in production, and relates to the same error the header has.

**Comment by josieg** [comment]
Adding a note that there is definitely a contact form in addition to the error notices that should not be on this page
![webform](https://user-images.githubusercontent.com/23706762/55521461-b0254a00-5635-11e9-8dcd-d6a1913f2897.jpg)

**Comment by bdolor** [comment]
there is nothing to be done on cert - it will resolve itself on prod when it can connect to the production database.
