### ISSUE TITLE
What is Open Education? page: Duplicate page, redundant link

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#180]
**Describe the bug**
On the "What is Open Education" page, there is a "Learn more" link that takes users to a different page that has the exact same content as the parent page.

**Additional context**
I checked the website content in Basecamp and the wireframes, and I don't think a "Learn more" link is supposed to be on the "What is open education" page. There definitely doesn't seem to be any unique content for it.

**To Reproduce**
1. Go to "What is Open Education." https://helga.bccampus.ca/wp/opentextbooks/what-is-open-education/
2. Click on "Learn More" 
3. The "Learn More" link takes you here: https://helga.bccampus.ca/wp/opentextbooks/what-is-open-education-2/ - This page has the exact same content as the parent page.

**Expected behavior**
I expect that there is no "Learn more" link and that this page (https://helga.bccampus.ca/wp/opentextbooks/what-is-open-education-2/) is deleted. 

**Screenshots**
![Screenshot_2019-04-03 What is Open Education – open UAT site](https://user-images.githubusercontent.com/23706762/55513015-852cfd00-5619-11e9-87f4-18334c3b8fd7.png)

**Comment by alex-418** [comment]
At first glance, I don't see anything in the code that would explain that behavior. Could you please delete that duplicate page, and then let me know if that resolves the issue?

**Comment by josieg** [comment]
I think there is a page that needs to be deleted, which is a non dev task. But do you @alex-418 have to remove the "Learn More" button? I assumed that part was hard coded. 

Also, if you up my permissions in this repo, I can label issues as a create them.

**Comment by alex-418** [comment]
The button takes the page ID and generates the URL automatically from that, so as long as the right page is assigned the links should all work as expected. In this case, I think the duplicate page is the issue, just want to rule that out before I dig any deeper into that. 

That sucks that you can't assign labels, looks like Github only allows people with write access to the repository to apply labels.

**Comment by alex-418** [comment]
@josieg can you see and assign labels on the right sidebar now?

**Comment by josieg** [comment]
No luck with the labels. But that's fine, don't worry about it. 

As for this issue, I'm pretty sure that we don't have a unique page for this "Learn more" button to link to. But can check with Erin to confirm.

**Comment by alex-418** [comment]
I see what you mean now, can definitely axe that learn more button if it's no necessary and that will be a dev task.

**Comment by alex-418** [comment]
@josieg removed the button
