### ISSUE TITLE
Canada's Open Education Initiatives: Apostrophe displaying as character string

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#183]
**Describe the bug**
The apostrophe in "Canada's Open Education Initiatives" is displaying as random characters in the tree (is that what it's called? I forget).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [Canada's Open Education Initiatives page](https://helga.bccampus.ca/wp/opentextbooks/what-is-open-education/canadas-open-education-initiatives/).
2. Look at the string of page titles at the top.
3. See Canada`&#8217;`s Open Education Initiatives

**Expected behavior**
I expect the apostrophe to be displaying properly.

**Screenshots**
![Screenshot_2019-04-03 Canada’s Open Education Initiatives – open UAT site](https://user-images.githubusercontent.com/23706762/55514607-67fa2d80-561d-11e9-8890-8aa7395e656a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Comment by alex-418** [comment]
Resolved via https://github.com/BCcampus/open-sage/commit/4d5c1a746239a929ea68ed584e37cb0c0b6eca33
