### ISSUE TITLE
Find Open Textbooks: MARC records and other collection 2-column cards

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#184]
**Describe the bug**
According to #16 , it was agreed to use two-column cards on the [Find Open Textbooks page](https://helga.bccampus.ca/wp/opentextbooks/2-0-find-open-textbooks/) to link to the Marc Records and Other Collections pages. I figured out how to set the column cards to the right pages in the customizer, but I could not figure out how to add the excerpt text to the column cards, set the featured images, or remove the hardcoded text above the column cards.

I think part of this issue is a non-dev task and part is a dev task. Will let Erin and Alex determine.
![marc](https://user-images.githubusercontent.com/23706762/55521063-f8dc0380-5633-11e9-85e8-61401491de09.jpg)

**Comment by alex-418** [comment]
@josieg Here's a screenshot of the customizer section that controls these. You can add an excerpt and featured image to these pages: 

![OER](https://user-images.githubusercontent.com/17072191/55577665-f1b30500-56c8-11e9-9cdd-d076ad156410.png)
 
As for the static text, if I recall this wasn't going to change often, so we left it static. @ehbeattie please confirm?

**Comment by josieg** [comment]
Hi Alex, I think the switch to column cards means that the above text is no longer needed. Erin can confirm though. 

And I found both of those pages. I see where to set a featured image, but I still don't see how to set the excerpt. Will let Erin handle it.

**Comment by alex-418** [comment]
@josieg oh, try seeing if it's enabled in your screen options (top right corner when editing that page).

**Comment by josieg** [comment]
Ahha! Thanks, fixed my problem!

**Comment by josieg** [comment]
I've updated the excerpts. @ehbeattie , can you confirm that it's okay to delete the duplicated text that precedes the column cards and update the featured images so they aren't the same?

**Comment by ehbeattie** [comment]
I'm not sure I 100% follow. Can you show me what you mean?

**Comment by josieg** [comment]
Now that the column cards have excerpts, the text preceding them is redundant and can be removed. 
![redundant](https://user-images.githubusercontent.com/23706762/55587673-b3294480-56e0-11e9-9676-2c48ab9fedd5.jpg)

**Comment by ehbeattie** [comment]
Ah, yes. I agree. Please feel free to delete.

**Comment by alex-418** [comment]
Removed via https://github.com/BCcampus/open-sage/commit/880dc2173ffb3e7fef07eb525ee4b2c8e0b1c134
