### ISSUE TITLE
Find open textbooks: Add text

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#187]
**Please add the following text just ABOVE the "Getting Started" heading on the "[Find Open Textbooks page](https://helga.bccampus.ca/wp/opentextbooks/2-0-find-open-textbooks/):** (Can copy the HTML from here: https://helga.bccampus.ca/wp/opentextbooks/2-0-find-open-textbooks/find-open-textbooks-resources/)

With a few hundred open textbooks available through the B.C. Open Textbook Collection, we felt it necessary to build in smart features to make it easier for you to choose, use, or modify open textbooks for your course.

Visit the B.C. Open Textbook Collection and select the resource that meets your needs, or use the keyword search to find the topic you’re looking for.

Filter options include:
- **Faculty Reviewed** – choose open textbooks that have been reviewed (link to call for reviews) and approved by instructors and faculty from B.C. and other provinces
- **Adopted** – find open textbooks that have been selected by instructors and added to their curriculum
- **Accessible** – open textbooks that meet the accessibility requirements outlined in the BCcampus Open Education Accessibility Toolkit
- **Ancillary Resources** – open textbooks with additional components, which could include quizzes, case studies, simulations, multi-media content, and other tools to help the learning process

**Comment by josieg** [comment]
Once this is done, I will delete this page: https://helga.bccampus.ca/wp/opentextbooks/2-0-find-open-textbooks/find-open-textbooks-resources/

**Comment by alex-418** [comment]
@josieg made that section editable from the editor via https://github.com/BCcampus/open-sage/commit/2441f54fce1622f0416024c60741c665844f0f0a, so you can copy paste the content from that page and it'll show up right above "Getting started". Let me know if that works as expected for you.

**Comment by josieg** [comment]
Worked perfectly! Thanks :)

**Comment by alex-418** [comment]
Awesome, no prob @josieg
