### ISSUE TITLE
Change the href of "Tell us you're using..." link from the application

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/open-sage#194]
**Describe the bug**
Currently, the open application links 
"Tell us you are using this Open Textbook " to
https://open.bccampus.ca/adoption-of-an-open-textbook

**Expected behavior**
Please link it to the page in the new architecture
https://open.bccampus.ca/use-open-textbooks/tell-us-youre-using-an-open-textbook/
instead.

**Screenshots**

![tell-us](https://user-images.githubusercontent.com/43043264/55828279-f27cda00-5ac0-11e9-8868-e568606ec426.png)

**Comment by bdolor** [comment]
complete
