### ISSUE TITLE
Change the href of "Support for adapting..." link from the application 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/open-sage#195]
**Describe the bug**
Currently, the open application links 
"Support for adapting an open textbook " to
https://open.bccampus.ca/open-textbook-101/adapting-an-open-textbook/

**Expected behavior**
Please link it to the page in the new architecture
https://open.bccampus.ca/use-open-textbooks/modify-adapt-an-open-textbook/
instead.

**Screenshots**
![adapt-link](https://user-images.githubusercontent.com/43043264/55830314-805ac400-5ac5-11e9-953c-eb3421bd97a6.png)

**Comment by bdolor** [comment]
complete
