### ISSUE TITLE
Wording change on Find Open Textbooks/Ancillary Resource page

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/open-sage#197]
**Is your feature request related to a problem? Please describe.**

When searching for all ancillary resources, this page appears, which is good:
https://open.bccampus.ca/browse-our-collection/find-open-textbooks/?lists=ancillary

But the text under the heading "Find Open Textbooks" needs to be changed. 

**Describe the solution you'd like**

Current text: "There are currently 136 ancillary textbooks."

Change text to: "**There are currently 136 textbooks with ancillary resources.**"

See image:

<img width="723" alt="OpenEd-Ancillary-wording" src="https://user-images.githubusercontent.com/26391359/55831031-0fb4a700-5ac7-11e9-8fe8-080592ea2aac.png">

**Comment by alex-418** [comment]
@paulagaube Fixed, please see https://open.bccampus.ca/browse-our-collection/find-open-textbooks/?lists=ancillary
