### ISSUE TITLE
Textbook reviews overlap on mobile

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/open-sage#198]
**Description**
Reviews of open textbooks don’t quite display right on mobile. The text overlaps (see screenshot). 

**To Reproduce**
1. Go to any textbook in the collection with a review at the bottom of the record page. 
2. Expand the review to see overlapping text. 

**Expected behavior**
Text does not overlap for easy readability. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44710357/55831805-d715cd00-5ac8-11e9-91da-85f0b6a71a55.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - Browser Safari

**Comment by alex-418** [comment]
Fixed via https://github.com/BCcampus/opentextbooks/pull/167

**Comment by alex-418** [comment]
@kkilbey Let me know if that fix works for you.

**Comment by kkilbey** [comment]
@alex-418 Looks awesome!
