### ISSUE TITLE
Open website: Featured Guides and Toolkits boxes no longer displaying books

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#202]
**Describe the bug**
On the open website, all boxes highlighting guides and toolkits are no longer displaying resources. I think this is related to me changing the subcategories under "Support Resources" :( Whoops.

The boxes on the following pages are broken:
- https://open.bccampus.ca/
- https://open.bccampus.ca/browse-our-collection/
- https://open.bccampus.ca/create-open-textbooks/

**Expected behavior**
It is expected that these boxes dynamically display the covers of support resources plus links to the resources. Similar to the "Latest Editions" box here: https://open.bccampus.ca/browse-our-collection/.

**Screenshots**
![guidesandtoolkitswebsite](https://user-images.githubusercontent.com/23706762/57659671-f906e180-7597-11e9-8cc3-e2b5fa930efc.jpg)

**Comment by alex-418** [comment]
@josieg Updated the Guides and Toolkits component to use of the new subcategories.

**Comment by josieg** [comment]
Awesome! However, the one on the home page is still not working. I believe the homepage one should be pulling from books that have the "featured guides and toolkits" checkbox checked in SOLR.

**Comment by alex-418** [comment]
@josieg "Faculty OER Toolkit" has this checked, and is display. Are there any others which have been set as "featured" that aren't showing up on the homepage? Please let me know which ones they are so I can troubleshoot that further.

**Comment by josieg** [comment]
Accessibility Toolkit - 2nd Edition, Self-Publishing Guide, Working Group Guide

**Comment by alex-418** [comment]
@josieg Fixed, let me know if that works as expected. Thanks!

**Comment by josieg** [comment]
Looks good!
