### ISSUE TITLE
Open Textbook Stats: Pressbooks

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#207]
**Describe the bug**
Under the "Pressbooks" tab on the [Open Textbooks Stats page](https://open.bccampus.ca/advocate-for-open-education/open-textbook-stats/), there are no books or stats displaying.

**To Reproduce**
1. Go to https://open.bccampus.ca/advocate-for-open-education/open-textbook-stats/
2. Click on the "Pressbooks" tab. 
3. See that there are no books listed.

**Expected behavior**
I expect that this page should be displaying the title, number of visits, number of actions, number of page views, and download stats for all books in the opentextbc.ca instance of Pressbooks.

**Screenshots**
![Pressbooks stats](https://user-images.githubusercontent.com/23706762/58122204-eefb6900-7bbd-11e9-8027-3ac3dbc8cd80.jpg)

**Comment by alex-418** [comment]
@josieg @dshaykewich Some interesting stuff going on with stats... the configuration on production points to our Matamo instance on troy.bccampus.ca/piwik but there's no tracking code on either open.bccampus.ca OR opentextbc.ca ... so as far as I can tell there's no data being collected for either. The stats page relies on the last 4 months of data, here's a graph of when the data stopped:

![download](https://user-images.githubusercontent.com/17072191/59542022-be56d880-8eb8-11e9-8de7-41e0d96d787b.png)

Do any of you have access to https://helga.bccampus.ca/piwik/ I want to see if maybe the sites are configured there?

**Comment by dshaykewich** [comment]
@alex-418 

https://jira.bccampus.ca/browse/SH-1301
-----------------------------------------------
 George Meyer added a comment - 11/Apr/19 10:32 AM

I have reviewed the guide and implemented some of the recommendations regarding database speed, and those that can be done on the existing server regarding server configuration.

**I am now looking into the setup of the of the tracker javascript to see if any changes on the front end can be suggested.**
-----------------------------------------------

**Comment by dshaykewich** [comment]
@alex-418  -- I don't seem to have an account in Matomo.

**Comment by josieg** [comment]
I don't have access. But maybe Paula or Kelsey?

**Comment by alex-418** [comment]
@josieg @dshaykewich updated API authentication token (stats were linked to an account that no longer exists) and data is flowing again 🚰
