### ISSUE TITLE
Question: Pressbooks stats on open site

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#210]
Hi! 

I have a question to determine if there is another possible bug on the stats page.

On the Pressbooks stats page on the open site (see "Pressbooks" tab here https://open.bccampus.ca/advocate-for-open-education/open-textbook-stats/), there are two different dates that are appearing:

1. At the very bottom of the list of textbooks, it says "Stats below based on the date range: 2019-03-02 to 2019-07-02" - (a four-month period).
2. But when you click on one of the "Download stats" icons, it says Downloads since Nov 2, 2018). (An 8-month period).

So my question is: Is the date range that's displaying for one of these options incorrect, or is the time period being shown just inconsistent.

**Comment by dshaykewich** [comment]
@josieg -- it's worse than that... it says "Downloads since Nov 2, 201**9**"

@alex-418 , let's look at this as a bug to tackle on Maintenance Monday.

**Comment by alex-418** [comment]
@josieg @dshaykewich Stats are back. Thanks @georgemeyer for fixing Matamo so quickly! The date range was set wrong in the code, so I have updated it and this resolved both the date shown when clicking the stats icon, and the date range at the end of the page as well.
