### ISSUE TITLE
New categories for the Open textbook collection

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#212]
Would you please add the following sub-categories to the open textbook collection in SOLR?

- Under "Language Learning" category add "Cree Language" subcategory 
- Under "Fine Arts" category add "Music" subcategory 
- Under "Communication/Writing" category  add "Creative Writing" subcategory 

Thanks!

**Comment by alex-418** [comment]
Done! Please give it a few minutes to update, the changes should be reflected soon and you will be able to assign books. The only difference is as discussed -- I've put "Music" in the "Art and Design" category.
