### ISSUE TITLE
New categories for the Open textbook Collection

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#214]
Hi Alex,
Please add the following categories to the open textbook collection:

**Under Education:**
- Diversity, Equity, and Inclusion

**Under Humanities:**
- Gender and Sexuality

**Under Language Learning:**
- Arabic Language 
- Korean Language

**Comment by alex-418** [comment]
@josieg I have added these categories just now.

**Comment by josieg** [comment]
Awesome! Thanks :)
