### ISSUE TITLE
Update hard-coded text on stats page on open site

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#215]
Hi Alex, 

When you get the chance, can you add the following definition to the ["Open Textbooks Stats" page](https://open.bccampus.ca/advocate-for-open-education/open-textbook-stats/) under the "Adoptions" tab. The definition should be inserted in between the "Adoption" definition and "Faculty" definition (see screen shot below). I believe the text is hardcoded. 
![book stats](https://user-images.githubusercontent.com/23706762/64970035-de9c8780-d859-11e9-98a6-01509c349f31.jpg)
Definition to insert:

**Book (refers to an open textbook)**
A comprehensive compilation of content organized into chapters that includes a table of contents, learning outcomes, and learning activities created to meet course objectives in a specific subject-area and is assigned an [open-copyright licence](https://creativecommons.org/) or released into the [public domain](https://en.wikipedia.org/wiki/Public_domain).

**Comment by alex-418** [comment]
Hi @josieg I've added this text to the stats page, thanks

**Comment by josieg** [comment]
Thanks Alex!
