### ISSUE TITLE
CAPTCHA broken on contact form

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/open-sage#217]
**Describe the bug**
An open.bccampus.ca user has reported that the CAPTCHA is not working in the Call for Reviewers contact form, on this page: https://open.bccampus.ca/use-open-textbooks/review-an-open-textbook/

**To Reproduce**
1. Go to https://open.bccampus.ca/use-open-textbooks/review-an-open-textbook/
2. Scroll down to the bottom of the page, where you'll see the contact form.
4. Note that the form asks you to "Type what you see below", but there is an error message that says, "To use CAPTCHA, you need Really Simple CAPTCHA plugin installed."

**Expected behavior**
The CAPTCHA displays correctly at the bottom of the form. The user completes the CAPTCHA and submits the form.

**Screenshots**
Instead, the user sees this:
![image](https://user-images.githubusercontent.com/44710357/70670919-5860c900-1c2f-11ea-9574-615255fc43df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

@dshaykewich assigning to you as per your email about reporting issues. Thank you! :)

**Comment by alex-418** [comment]
@kkilbey This has now been fixed. Please confirm

**Comment by kkilbey** [comment]
Thanks @alex-418! Now I don't see any CAPTCHA--is that correct?
![image](https://user-images.githubusercontent.com/44710357/70671316-7c70da00-1c30-11ea-82b4-e369f5c7b975.png)

**Comment by alex-418** [comment]
@kkilbey Correct. reCaptcha v3 works behind the scenes. Will only challenge bots. You should also now see this: 

![privacy](https://user-images.githubusercontent.com/17072191/70671374-b17d2c80-1c30-11ea-9b5e-cc23a077b13a.png)

**Comment by kkilbey** [comment]
Fastest ticket open/close ever! Awesome, thanks again @alex-418 :)

**Comment by alex-418** [comment]
![quick_draw](https://user-images.githubusercontent.com/17072191/70671667-a4ad0880-1c31-11ea-9842-d3eecaa2691a.gif)
