### ISSUE TITLE
New category for OT Collection: Ocean Studies

### ISSUE THREAD

**Issue by acheveldave** [BCcampus/open-sage#220]
Hi @alex-418! When you get the chance, would you be able to add a new category to the open textbook collection?

Please add "Ocean Studies" as a sub category to "Earth and Ocean Sciences."

Thanks,
Arianna

**Comment by alex-418** [comment]
@acheveldave This new category has been added, thanks.

**Comment by acheveldave** [comment]
@alex-418 Thank you!
