### ISSUE TITLE
New sub category for OT Collection: "Computer Science - General"

### ISSUE THREAD

**Issue by acheveldave** [BCcampus/open-sage#222]
Hi @alex-418! Would you please add to the collection "Computer Science - General" as a sub category under "Computer Science" when you get the chance? Thank you!

**Comment by alex-418** [comment]
Hi @acheveldave sure can, just to confirm... do you want is exactly as "Computer Science - General" or just "General" under computer science? Thanks

**Comment by acheveldave** [comment]
Hi @alex-418, following the convention in the collection when creating a general sub category, we'd like it as "Computer Science - General," please. Thank you!

**Comment by alex-418** [comment]
The new sub category has now been added.

**Comment by acheveldave** [comment]
Thank you!
