### ISSUE TITLE
Blade Template: Use Open Textbooks

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#24]

**Comment by bdolor** [comment]
Can be validated at https://helga.bccampus.ca/wp/opentextbooks/use-open-textbooks 

but really, I think we can all agree we pretty much nailed it here: 

![image](https://user-images.githubusercontent.com/2048170/52447581-fa7ec480-2ae5-11e9-9e78-507db3f728a3.png)

**Comment by alex-418** [comment]
Re-opening to tackle the static text and 3-column cards with links

**Comment by alex-418** [comment]
Will be completed once https://github.com/BCcampus/open-sage/pull/96 is merged, but i'm missing the static  placeholder text in the mid-section.

**Comment by alex-418** [comment]
@josieg to provide text for the mid-section

**Comment by josieg** [comment]
Middle section content: Open textbooks in the B.C. Open Textbook Collection come in multiple formats. Many can be read online or delivered via PDF, EPUB (for most e-readers) and MOBI (for Kindle) format for free, or can be printed via our print-on-demand service for a nominal fee.
