### ISSUE TITLE
Use Open Textbooks page: 2-column cards for "In a Class" and "In an institution"

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#26]
Can reuse styling from the homepage 2-column cards. Learn more links go to: 
- "Use an open textbook in a class" page.
- "Use open textbooks in an institution" page.

**Comment by alex-418** [comment]
Add option in customizer to add page ID's of the cards.

**Comment by ehbeattie** [comment]
Here's the content: 

**In a class**
Learn how to find, choose, and modify open textbooks to help decrease the financial impact on students while providing an improved learning experience. [learn more] – links to 3.1 use an open textbook in class

**In an institution**
Read about adopting open textbooks, creating OER policies, and how to assess your institution’s capacity for OER. [learn more] – links to 3.2 use an open textbook in your institution

Open textbooks in the B.C. Open Textbook Collection can be read online or delivered via PDF, EPUB (for most e-readers) and MOBI (for Kindle) format for free, or for a nominal fee, can be printed via our print-on-demand service. 

**Faculty open educational resources (OER) toolkits**
Refer to these useful guides to learn more about self-publishing, adopting, and adapting open textbooks and other OER.

- Self-Publishing Guide
- Adaption Guide
- Adoption Guide

**Comment by alex-418** [comment]
Completed via #95 please note the following and see screenshot below: 

The "Use Open Textbooks" page must exist and be set to use the "Use OER" template... then to set the left and right cards as per design, you can visit the customizer menu (under appearance) and set the correct pages. Those pages must exist and have the excerpts as provided in https://github.com/BCcampus/open-sage/issues/26#issuecomment-458273166 with a featured image so they show up as expected on the "Use Open Textbooks" page. 

![use_open](https://user-images.githubusercontent.com/17072191/53373307-ea4e4e00-3909-11e9-94ac-bacb0eb98fe8.png)

**Comment by ehbeattie** [comment]
Is there a page I can look at to view this in action?

**Comment by alex-418** [comment]
@ehbeattie Sure, so I provided the instructions above in https://github.com/BCcampus/open-sage/issues/26#issuecomment-467211499 in hopes that whoever was adding the content could ensure/validate that you had full control of this. It requires creating the correct pages, content, excerpt, featured images, and validating that the customizer options worked well. Let me know if you need more help or a quick walk through on this.

**Comment by ehbeattie** [comment]
In essence of time... is there a faster workaround?

**Comment by alex-418** [comment]
I could validate this myself... but would prefer someone who's working on content does so they're familiar with how pages work,  because that will be needed when it's time to put content on production. This could also satisfy part of https://github.com/BCcampus/open-sage/issues/103

**Comment by ehbeattie** [comment]
Tested and validated. 👍
