### ISSUE TITLE
[Footer] social media component

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#27]
social media icons and links to various social media platforms. + logo. 

twitter handle is bcopentext

**Comment by alex-418** [comment]
Same as bccampus.ca (the only difference is the twitter handle)

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/open-sage/commit/1b716b2ad1d28d144c2dd2be26b0ce0953845e2e

**Comment by ehbeattie** [comment]
Gorgeous.
