### ISSUE TITLE
[Footer] black area privacy and terms and conditions creative commons license

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#28]
create the footer component as per mockup

**Comment by alex-418** [comment]
Same as bccampus.ca

**Comment by alex-418** [comment]
Moved to validating as this was tackled as part of #4

**Comment by ehbeattie** [comment]
Can Mar/Com have access to the privacy and terms pages to edit them? Also, the footer is looking a little wonky. See attached: 
![screen shot 2019-02-07 at 1 09 46 pm](https://user-images.githubusercontent.com/44707412/52443098-ae2d8780-2ad9-11e9-80a9-7f2f58879ee0.png)

**Comment by bdolor** [comment]
@ehbeattie my understanding is that you can determine which menu is displayed at that footer location. You would control that through the 'Customize' option...

![image](https://user-images.githubusercontent.com/2048170/52447187-e4243900-2ae4-11e9-9680-6d3fe6c140ad.png)

You can select which menu goes there, and then in the menus dashboard, edit the menu items. Play around with that, and if it solves the issue for you feel free to drag this to the appropriate column.

**Comment by ehbeattie** [comment]
@bdolor - Ok, but the 'footer terms menu' shows only one page linked to it, titled 'terms, but when I save the menu, it shows multiple pages.

**Comment by bdolor** [comment]
prolly easier if I do it. ok done.

**Comment by alex-418** [comment]
@ehbeattie terms page is now showing up, and menus are working as expected. This was due to a glitch with WordPress menus, resetting them did the trick.
