### ISSUE TITLE
Textbook cover images

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#29]
**What is the current behavior?**

There are many instances of textbook covers throughout the theme.

**What is the expected or desired behavior?**

Without a place to grab pre-existing cover images we need a way to generate small unique textbook covers. 

Create a system whereby titles of textbooks can be placed in front of/on top of a static textbook cover image.

Note: there is a nice to have feature for adding 'new' and 'updated' labels put at the top left of cover images. Questions are what is `new` and what is `updated`...how/where is it controlled?

**Comment by bdolor** [comment]
It occurs to me that it may be relatively straight forward if the opentextbook application is brought in as a dependency of the theme as per https://github.com/BCcampus/open-sage/commit/526ef330c7afe0b8b177635ff72e26bf63cc004b

**Comment by ehbeattie** [comment]
Here's a generic cover image for testing this. 

![textbook-cover](https://user-images.githubusercontent.com/44707412/51498126-46a5d700-1d7a-11e9-975b-0854a393438d.jpg)

**Comment by alex-418** [comment]
To come from WordPress, custom image size of 151x196 is needed(we might have a function that handles this already)
