### ISSUE TITLE
Main menu - 2 level nested items 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#3]
Using the sitemap located in the template markup create a two level dropdown menu.

**Comment by bdolor** [comment]
![image](https://user-images.githubusercontent.com/2048170/51855836-0b0f8d80-22e3-11e9-8f62-e6945cd3a1cb.png)

**Comment by alex-418** [comment]
Please note: Clearing your browsers cache may be required to see new changes take effect.

**Comment by alex-418** [comment]
Here's what you should expect to see for the menu on Helga on desktop:
![desktop_menu](https://user-images.githubusercontent.com/17072191/52506090-3c6d4080-2ba2-11e9-8f20-3e575940ed95.png)

Here's where I landed for on the mobile menu: 
![mobile_menu](https://user-images.githubusercontent.com/17072191/52506118-5ad33c00-2ba2-11e9-8480-5245e0e22f7b.png)

**Comment by alex-418** [comment]
Discussed with @ehbeattie that blue underline is not important. Leaving that out.

**Comment by alex-418** [comment]
Main nav links need to be black 
Links need to be dark blue 
hover needs to be light blue

**Comment by alex-418** [comment]
@ehbeattie updated, please see below. 

Main Nav is now black:
![main-nav-black](https://user-images.githubusercontent.com/17072191/52509228-39774d80-2bac-11e9-9075-383b625e2504.png)

Main nav hover:
![main-nav-hover](https://user-images.githubusercontent.com/17072191/52509242-485e0000-2bac-11e9-89f3-f13008222404.png)

Sub nav hover:
![sub-nav-hover](https://user-images.githubusercontent.com/17072191/52509247-4a27c380-2bac-11e9-9823-96236f2a5629.png)

**Comment by ehbeattie** [comment]
This looks much better, thanks, @alex-418
