### ISSUE TITLE
Find Open Textbooks Page: content

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#30]
as per the template, content on the page is as follows: 

**Find open textbooks**
The B.C. Open Textbook Collection is home to a growing selection of open textbooks for a variety of subjects and specialties. Use the filter tool to find open textbooks that have been reviewed by faculty, meet our accessibility requirements, or include ancillary materials (quizzes, test banks, slides, videos, etc.).

**B.C. open textbook MARC records**
Gain access to machine-readable cataloguing (MARC) records for all of the content created for BCcampus Open Education.

**Other collections**
New additions to the B.C. Open Textbook Collection are added regularly, and we’ve compiled a list of open textbook libraries to connect you with the open educational resources (OER) you may need for your institution. 

where ever possible, will hand over content control to content owners.

**Comment by alex-418** [comment]
@ehbeattie confirm if this is the content we will use for 2.0

**Comment by ehbeattie** [comment]
Content: 

**Find open textbooks**
The B.C. Open Textbook Collection is home to a growing selection of open textbooks for a variety of subjects and specialties. Discover open textbooks that have been reviewed by faculty, meet our accessibility requirements, and/or include ancillary materials (quizzes, test banks, slides, videos, etc.).

**B.C. open textbook MARC records**
Gain access to machine-readable cataloguing (MARC) records for all of the content created for BCcampus Open Education.

**Other collections**
The B.C. Open Textbook Collection continues to expand, so we’ve compiled a list of open textbook libraries to connect you with the open educational resources (OER) you may need for your institution.

**Comment by ehbeattie** [comment]
Over to you, @alex-418

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/open-sage/commit/ec23b6e8cdfa0e77cb3dcb5f66a4a223064b95e7 

validation at https://helga.bccampus.ca/wp/opentextbooks/open-textbooks-2/

**Comment by ehbeattie** [comment]
It's coming along nicely. Good work!
