### ISSUE TITLE
[62.1] Find an Open Textbook page: Guides and Toolkits component

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#31]
randomize three Guides and Toolkits - the potential feature for adding new and updated labels is captured in https://github.com/BCcampus/open-sage/issues/29

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/open-sage/pull/100 

can be validated at https://helga.bccampus.ca/wp/opentextbooks/open-textbooks-2/ - refreshing page will trigger a random list of guide and toolkit books

**Comment by ehbeattie** [comment]
Oooh, fancy.
