### ISSUE TITLE
Create online submission form for ancillary resource requests.

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/open-sage#34]
**Is your feature request related to a problem? Please describe.**
Non-Dev task.

Instructor/faculty members are directed to email helpdesk@bccampus.ca to request ancillary resources (e.g., test banks).  They often do not include sufficient information in their request or do not specify which institution they belong to, which requires support staff to write back to request more information. This exchange often takes multiple emails to complete.

**Describe the solution you'd like**
Create an online submission form that includes all the information required to make a request for ancillary resources. 

**Describe alternatives you've considered**
Clarifying the requirements on the website has been considered, but the main information is there already and still people do not comply with the requirements (e.g., using an institutional email address, and our requirement to confirm they belong to an institution.)

**Additional context**

As a member of the open support team
I would like to receive complete requests from users who want ancillary resources
So that I only need to send one email to them to complete the request.

**Comment by paulagaube** [comment]
- Suggest setting up a new form in Contact Form 7 form for ancillary resource requests.
- Make sure honeypot is installed.
- Add a public note that we require requests to come from an institutional email address and we will verify instructor/faculty status using the institution's online directory.
- Decide if we want to include wording that says we will consider special requests from non-instructors.

**Comment by paulagaube** [comment]
Ancillary Requests page with submission form has been created on Prod:
https://open.bccampus.ca/ancillary-requests/

Ancillary Requests page with submission form on Helga does not have the CSS styling needed for the [box] tag:
https://helga.bccampus.ca/wp/opentextbooks/ancillary-requests/

**Comment by paulagaube** [comment]
@alex-418 @ehbeattie Now that we've created a new Ancillary Request page and form, we need to replace the links that say "Email helpdesk" on each of the resources that have restricted ancillary resources. 
e.g., https://open.bccampus.ca/find-open-textbooks/?uuid=8390d51e-0efe-493c-881c-cf86852a612f&contributor=&keyword=&subject=Psychology

The MAILTO: link can go to the new "Ancillary Requests" page instead: https://open.bccampus.ca/ancillary-requests/
I think this is a DEV task?

<img width="479" alt="ancillary-requests-helpdesk" src="https://user-images.githubusercontent.com/26391359/55019718-a60aa800-4fb2-11e9-8853-80f12af6648a.png">

**Comment by kkilbey** [comment]
These are all the textbook record pages that say "Email helpdesk" and will need to be updated to the new ancillary request page:
- [Adult Literacy Fundamentals Mathematics: Book 1](https://open.bccampus.ca/find-open-textbooks/?uuid=1eade072-4b30-4c2e-b3d8-cb2512765e8d)
- [Adult Literacy Fundamentals Mathematics: Book 2](https://open.bccampus.ca/find-open-textbooks/?uuid=65ad18bb-686d-4cb5-b85a-361a326b69bb)
- [Adult Literacy Fundamentals Mathematics: Book 3](https://open.bccampus.ca/find-open-textbooks/?uuid=0dea611f-6f9c-4d7e-a700-e5c7adcc86e5)
- [Adult Literacy Fundamentals Mathematics: Book 4](https://open.bccampus.ca/find-open-textbooks/?uuid=f2ccf504-86e6-4ebc-9d39-63eaf9695d72)
- [Adult Literacy Fundamentals Mathematics: Book 5](https://open.bccampus.ca/find-open-textbooks/?uuid=4e8eeb05-62dd-4aa0-a749-eaf5595d7bbf)
- [Adult Literacy Fundamentals Mathematics: Book 6](https://open.bccampus.ca/find-open-textbooks/?uuid=45904857-90cc-4660-8863-9bae2be105e3)
- [Beginning Excel](https://open.bccampus.ca/find-open-textbooks/?uuid=80256b78-e7fa-4956-925b-485363c1bc97)
- [Business Math: A Step-by-Step Handbook](https://open.bccampus.ca/find-open-textbooks/?uuid=16301119-8ec4-4241-b0f7-cc87ffc942d6)
- [College Physics](https://open.bccampus.ca/find-open-textbooks/?uuid=c0cd5405-a301-4940-ab3a-56f754a0030a)
- [College Skills: Intermediate English](https://open.bccampus.ca/find-open-textbooks/?uuid=50c06bda-f743-43f1-97d8-60014a91f51e)
- [Concepts of Biology - 1st Canadian Edition](https://open.bccampus.ca/find-open-textbooks/?uuid=a2086095-a679-4e33-b0dd-f5b96192fba1)
- [Basic Kitchen and Food Service Management](https://open.bccampus.ca/find-open-textbooks/?uuid=390f5e1a-8ec4-45cf-9caf-b692536add2d)
- [Food Safety, Sanitation, and Personal Hygiene](https://open.bccampus.ca/find-open-textbooks/?uuid=f8ac1b54-f348-4109-8176-203988432864)
- [Human Resources in the Food Service and Hospitality Industry](https://open.bccampus.ca/find-open-textbooks/?uuid=83a1ea7d-0c57-4653-a572-25351671ae59)
- [Meat Cutting and Processing for Food Service](https://open.bccampus.ca/find-open-textbooks/?uuid=8762ccf0-5053-43e9-a256-433b2bdcc4bd)
- [Modern Pastry and Plated Dessert Techniques](https://open.bccampus.ca/find-open-textbooks/?uuid=085e3447-fba6-4254-8c6b-394ca36d2fd7)
- [Nutrition and Labelling for the Canadian Baker](https://open.bccampus.ca/find-open-textbooks/?uuid=3bb22917-ec4b-4ef5-b649-84c296a9765a)
- [Understanding Ingredients for the Canadian Baker](https://open.bccampus.ca/find-open-textbooks/?uuid=168f1166-adcd-4498-b9a1-950ae74281d7)
- [Working in the Food Service Industry](https://open.bccampus.ca/find-open-textbooks/?uuid=9e64cb26-2a96-4370-8c38-5945fe1ca74a)
- [Workplace Safety in the Food Service Industry](https://open.bccampus.ca/find-open-textbooks/?uuid=8e16635e-8041-4986-8872-f16cce8d3781)
- [Introduction to Sociology, 2nd Canadian Edition](https://open.bccampus.ca/find-open-textbooks/?uuid=6140c265-61a6-455b-80b8-6ec8fcdf5a48)
- [Introduction to Psychology - 1st Canadian Edition](https://open.bccampus.ca/find-open-textbooks/?uuid=8390d51e-0efe-493c-881c-cf86852a612f)
- [Introduction to Psychology](https://open.bccampus.ca/find-open-textbooks/?uuid=13c9299c-0f96-4403-bf76-6989127c6620)

**Comment by josieg** [comment]
This is a non-dev task. See this issue I created: https://github.com/BCcampus/opentextbooks/issues/160

**Comment by kkilbey** [comment]
Awesome, thanks @josieg! We missed that issue. Let us know if we can help with that task. :)

Since this ticket is just related to creating the Ancillary Resource Request form, perhaps we could move it to Validating? @paulagaube

**Comment by paulagaube** [comment]
@ehbeattie @alex-418 This issue is done, but the Non-Dev issue from @josieg https://github.com/BCcampus/opentextbooks/issues/160 needs to be done as well. Can we bring that into this sprint please?

**Comment by kkilbey** [comment]
I've updated the Ancillary Resource Request pages/forms on Prod and Helga with feedback from Lauri and Josie. Moving this ticket to Validating.
