### ISSUE TITLE
UAT env set up

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#37]
**Is your feature request related to a problem? Please describe.**
UAT environment set up

**Describe the solution you'd like**
We need to set up helga site, import content, integrate jenkins, create user accounts

**Comment by bdolor** [comment]
UAT environment set up at https://helga.bccampus.ca/wp/opentextbooks

**Comment by paulagaube** [comment]
I have confirmed this link works, and that is a HUGE photo of Rajiv. Such a happy photo. :)
<img width="303" alt="open-helga-rajiv" src="https://user-images.githubusercontent.com/26391359/52070716-4f469c00-2536-11e9-8722-bbffe1af349a.png">
