### ISSUE TITLE
Content: Remove all references to emailing Helpdesk (and include a link to Need Help? or Contact form(s) as required)

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/open-sage#39]
**Is your feature request related to a problem? Please describe.**
Non-Dev/Content task
BCcampus is phasing out the term "Helpdesk" and the "Helpdesk@bccampus.ca" email address. 

In the Open website content, the exposed email address "Helpdesk@bccampus.ca" has been used to direct people to contact the Helpdesk when users have issues, questions, or request ancillary resources.  We need to remove these references and replace with alternate contact information or help pages.

**Describe the solution you'd like**
Remove all references to Helpdesk. Add links to a new "Need Help?" page and appropriate "Contact Us" form(s).

**Describe alternatives you've considered**
None. The Helpdesk is being phased out. Now is the time to change this.

**Additional context**

As an Open website user,
I would like to know where and how to get help and support
So that I can get help to find resources, report issues, or request ancillary resources easily.

As a member of the BCcampus Support team, 
I would like to be able to see all requests that come from the Open website in one place, with complete information, in context, 
So that I can quickly respond to the user's needs.

**Comment by kkilbey** [comment]
I've reviewed the content in Basecamp and found instances of "Helpdesk" on the following pages:
- 3.5 Open Education Mailing Lists ("helpdesk" in Google doc but not on helga?)
- 6.3 Completed OpenEd Projects (replace 6 instances of "helpdesk" email address with ancillary resource request form)
- ~~All textbook record pages for books with ancillary materials (this work captured in #34).~~ Josie working on this; see https://github.com/BCcampus/opentextbooks/issues/160

We have to create a new contact form and an ancillary resource request form before updating these pages. Just noting them here for reference!

**Comment by kkilbey** [comment]
I have updated both pages noted above to remove references to "Helpdesk." Links for validating:
- https://helga.bccampus.ca/wp/opentextbooks/use-open-textbooks/open-education-mailing-lists/
- https://helga.bccampus.ca/wp/opentextbooks/projects-and-grants/completed-opened-projects/

There is another version of the Mailing List page on Helga that I believe is outdated. Perhaps we could delete this page? Link: https://helga.bccampus.ca/wp/opentextbooks/b-c-institutions-open-education-mailing-lists/
