### ISSUE TITLE
[Footer] Create subscribe component in footer

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#40]
As per mockup (similar to bccampus.ca), need the campaign monitor code to that generates the button.

**Comment by alex-418** [comment]
@ehbeattie If you send over campaign monitor credentials I can tackle this one fairly quickly.

**Comment by ehbeattie** [comment]
Hi @alex-418 - I've added you as a user. Please let me know if that's all you need.

**Comment by alex-418** [comment]
@ehbeattie thank you, is there an existing list at https://bccampus.createsend.com/subscribers/ that I could use to generate the form? Or would you like me to create a new one.

**Comment by ehbeattie** [comment]
Does this help? https://bccampus.createsend.com/subscribers/subscribeProcess.aspx?listID=97f887551c7932f2

**Comment by alex-418** [comment]
Yes thank you @ehbeattie that tells me which list you are using so I can generate the form for that so we have the subscribe button. Those settings that you link to are also important, that's where you will set the page on our website that it sends them to when they hit the subscribe button, and also the success page on our website. For now I will use placeholders on helga, these will have to be updated once the pages exists on production.

**Comment by ehbeattie** [comment]
Ok, perfect. Thanks!

**Comment by alex-418** [comment]
@ehbeattie This is ready for validation, and includes all of the subscribe related issues, except I will put #4 back because i did not apply the settings to re-direct the subscription, leaving that up to you guys. Once you are ready to test, just update the settings in campaign monitor as per screenshot below, and hit the subscribe button on the footer!

I would also like to request a review of the form fields... the form seemed a bit long to me, and found it strange to ask for the IP? 

Please note the following: 

1. [subscribe](https://helga.bccampus.ca/wp/opentextbooks/subscribe/) and [subscribe-confirm](https://helga.bccampus.ca/wp/opentextbooks/subscribe-confirm) pages needs to exists on the website and have the correct templated assigned. I have done this for you on Helga, you will need to do it on production, please see screenshot below to see the correct template that the `subscribe` page needs: 

![template](https://user-images.githubusercontent.com/17072191/52313465-769ccf00-2963-11e9-92a3-e1366aa34ef1.png)

2. Settings for the subscribe button and confirmation page need to be updated so the subscribe button (and confirmation button) take them to the correct pages on the website. 

Here's an example of what the correct settings would be for helga (note: I did not apply these, but I did create the pages on Helga for you, so just updating these settings is all you need to do)

![campaign_monitor](https://user-images.githubusercontent.com/17072191/52313895-258dda80-2965-11e9-8fa5-7f82161bd21b.png)
*typo in confirmed URL. It should read `/subscribe-confirm` the reason page name is important, is that I excluded the breadcrumbs from these pages in the theme. 

Once you are ready to test, just update the settings in campaign monitor, and hit the subscribe button on the footer!

**Comment by alex-418** [comment]
Also please let me know if the subscribe text in the footer needs to be updated: 
![subscribe_text](https://user-images.githubusercontent.com/17072191/52314218-9c77a300-2966-11e9-80ea-6ec55b61e54c.png)

**Comment by ehbeattie** [comment]
Looks great!
