### ISSUE TITLE
styling of the homepage

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#49]
**Is your feature request related to a problem? Please describe.**
Styling as we go proves to be difficult when components on the same page have the ability to effect one another.

**Describe the solution you'd like**
Once the homepage components are in place, attention to the styling of the whole page can be addressed, including a consistent mobile experience. 

**Describe alternatives you've considered**
Trying to perfect styling before all items are built was identified as an area for improvement in the last web site build. 

**Additional context**
As a developer
I would like to approach page design after all components and functionality is complete
So that I can reduce duplication of effort

**Comment by alex-418** [comment]
Made some changes to the homepage (and also affect the whole site) please let me know if you notice anything else that needs to be fixed! 

Buttons:
Colors updated to match design

Padding/Margin:
Updated to closely match design, not exact since design did not consider tablet/mobile 

Card Headings:
Font weight made lighter 

Card Images:
Fixed the issue when hovering the heading links were being underlined

**Comment by ehbeattie** [comment]
Add a period after the sentence, here: 
<img width="508" alt="Screen Shot 2019-03-22 at 12 48 38 PM" src="https://user-images.githubusercontent.com/44707412/54849226-dbf11900-4ca0-11e9-8cfd-8e66e9456f1f.png">

**Comment by ehbeattie** [comment]
Make sure there is the proper numbering, such as: $1,459,800
<img width="337" alt="Screen Shot 2019-03-22 at 12 49 09 PM" src="https://user-images.githubusercontent.com/44707412/54849302-135fc580-4ca1-11e9-9b69-dc574ad5debf.png">

**Comment by ehbeattie** [comment]
Add the periods in B.C. Open Textbook Collection 
<img width="599" alt="Screen Shot 2019-03-22 at 12 55 08 PM" src="https://user-images.githubusercontent.com/44707412/54849535-cc260480-4ca1-11e9-8a2b-d033c46a7e20.png">

**Comment by alex-418** [comment]
> Add a period after the sentence, here:
> <img alt="Screen Shot 2019-03-22 at 12 48 38 PM" width="508" src="https://user-images.githubusercontent.com/44707412/54849226-dbf11900-4ca0-11e9-8cfd-8e66e9456f1f.png">

This content for the quote comes from the assigned pages excerpt, it can be updated there.

**Comment by alex-418** [comment]
> Add the periods in B.C. Open Textbook Collection
> <img alt="Screen Shot 2019-03-22 at 12 55 08 PM" width="599" src="https://user-images.githubusercontent.com/44707412/54849535-cc260480-4ca1-11e9-8a2b-d033c46a7e20.png">

Completed via https://github.com/BCcampus/open-sage/commit/080fe12f465e4ce78adf6baf8c53933d5812a98e

**Comment by alex-418** [comment]
> Make sure there is the proper numbering, such as: $1,459,800

As discussed split this off into it's own issue here: https://github.com/BCcampus/open-sage/issues/151
