### ISSUE TITLE
[Homepage] Header Hero image and textbox 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#5]
Let the user control it, only displays one at a time. Pull heading and content from a post that is in a specific category and sticky. 50% image 50% text (aka halfsies)

**Comment by murphybarb** [comment]
**Heading:** 
Find open textbooks
**Body Copy:** 
Discover a few hundred open textbooks available for you to choose, use, or modify for your students.

**Comment by bdolor** [comment]
![image](https://user-images.githubusercontent.com/2048170/51856577-ea483780-22e4-11e9-835c-5daca7fba5db.png)

**Comment by alex-418** [comment]
@bdolor Would prefer to tackle this with a user option in the "Home Page Settings" customizer menu to let the user enter either the page ID, or select from a list of pages. This would deviate from the category/stick post route in the original description. Any objections?

**Comment by alex-418** [comment]
Completed via #44 

![page_select](https://user-images.githubusercontent.com/17072191/52021410-d26de080-24a9-11e9-9862-a7f1765cf95d.png)
