### ISSUE TITLE
Homepage: Search under the hero image

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#6]
Create a search box that has a dropdown filter with the following filters:

Keyword (api: keyword)
Title(not clear if we can get from api)
Author(api: contributor)
Subject (api: subject)

**Comment by bdolor** [comment]
Pending further investigation it is the case that searching by subject area needs to be an exact string match and searching by title only is not possible. 

Requires more investigation into the limitations of the search api provided at http://solr.bccampus.ca:8001/bcc/apidocs.do

**Comment by bdolor** [comment]
![image](https://user-images.githubusercontent.com/2048170/51856758-562aa000-22e5-11e9-9c5b-3d474a2c0225.png)

**Comment by bdolor** [comment]
can commit to semi-fuzzy search for subject, author and title with the API limitation that `like` queries can _not_ start with a wildcard. Difference being that a search target like `A.W. (Tony) Bates` will return on a search for `A.W.*` but not `Tony*` 

keyword, is fine...if what is meant by that is if that the word exists anywhere in the title or description (what is already the default behavior)
