### ISSUE TITLE
[62] As an instructor I would like access to the guides and toolkits to be really efficient so that I can benefit from the information contained within them

### ISSUE THREAD

**Issue by bdolor** [BCcampus/open-sage#62]
**Conditions of Satisfaction**

Create components that link back to all guides and toolkits

- [ ] Pg. 4 in open.Bccampus.ca template markup
- [ ] `homepage` (pg.3)
- [ ] 2 places on `create open textbooks` (pg.8)

![image](https://user-images.githubusercontent.com/2048170/52733990-f4229980-2f78-11e9-9668-a2728cea692a.png)

**Comment by bdolor** [comment]
@ehbeattie @dshaykewich would like to propose broadening the user story and increasing the conditions of satisfaction. 

I notice there are a few places other than page 4 in the mockup that provide places to display 'links to guides and toolkits'. They are:
- `homepage` (pg.3)
- `use open textbooks` page (pg.7)
- 2 places on `create open textbooks` (pg.8)

Either this user story needs to include these conditions of satisfaction, or if they are intended to be captured in alternative user stories then we need to look at creating those. Depending on which way you go, the new user story could be `As an instructor I would like access to the guides and toolkits to be really efficient so that I can benefit from the information contained within them.`

**Comment by ehbeattie** [comment]
@bdolor - I'm not sure what to do with this one. @dshaykewich - thoughts? 

Is there too much onus on the guides and toolkits?
