### ISSUE TITLE
[68] As an Open website user with different abilities, I would like the Open website to conform to WCAG2.0 Level AA, so that I can use the site to find resources for my learning experiences

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#68]
**Conditions of Satisfaction**

Site meets at minimum WCAG 2.0 Level AA. 
https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aa%2Caaa&versions=2.0#top

For this site, particularly relevant for:
Guideline 1.1 - Text Alternatives
Guideline 1.3 - Adaptable
Guideline 1.4 - Distinguishable
Guideline 2.1 - Keyboard Accessible
Guideline 2.3 - Seizures and Physical Reactions
Guideline 2.4 - Navigable
Guideline 3.1 - Readable
Guideline 3.2 - Predictable
Guideline 3.3 - Input Assistance
Guideline 4.1 - Compatable

**Comment by ehbeattie** [comment]
Again, I'll have to trust you on this one. :)
