### ISSUE TITLE
Homepage: 2-column cards under search: "Create" and "Use" Open Textbooks

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#7]
Create 2-column bootstrap cards as per design. Pulls title, excerpt ,featured image from parent page. Button links to the parent page. 

Note: text must pull from excerpt and not page content.

**Comment by murphybarb** [comment]
Content

**Head:** 
Create open textbooks
**Body copy:** 
Contribute your expertise to the global knowledge base by creating and sharing an open textbook.

**Head:** 
Use open textbooks
**Body Copy:** 
Choose an open textbook to provide your students with an affordable, accessible, and engaging learning experience.

**Comment by bdolor** [comment]
![image](https://user-images.githubusercontent.com/2048170/51857006-039db380-22e6-11e9-9720-36775fd98071.png)

**Comment by alex-418** [comment]
3rd card to be determined

**Comment by alex-418** [comment]
Add option to customizer in the homepage section to enter the Page ID's of the cards. This will pull in the content of the cards.

**Comment by alex-418** [comment]
Following the same pattern as #5 so this will live in the customizer.
