### ISSUE TITLE
[74.0] As a instructor, I would like to see the licence of each open textbook so that so that I know how I may use the materials 

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/open-sage#74]
**Conditions of Satisfaction**

- On the resource details page, display the appropriate open license logo and license description for the resource

![license-logo](https://user-images.githubusercontent.com/43043264/53134036-4be97380-352a-11e9-9629-a69d56c8b00c.png)

**Comment by alex-418** [comment]
Removing, already exists no work needed.
