### ISSUE TITLE
[77] As a instructor, I would like to see the available formats for a resource so that I can choose the best format for my teaching.

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/open-sage#77]
**Conditions of Satisfaction**

1. Show in a sidebar
2. Categorized by "Readable" and "Editable" (cannot commit to Ancillary because we have no way to tell them apart)
3. Button link to print on demand titled "Buy a print copy" (only if it exists) 

Discussion: https://github.com/BCcampus/opentextbooks/issues/126 

![getthisbook](https://user-images.githubusercontent.com/43043264/53134751-3a559b00-352d-11e9-88d3-4157ac48e796.png)

**Comment by alex-418** [comment]
Included in https://github.com/BCcampus/opentextbooks/issues/137
