### ISSUE TITLE
[78] As a instructor, I would like to see the details of textbook so that I can assess whether this textbook will work well for my teaching

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/open-sage#78]
**Conditions of Satisfaction**
Resource details page displays:

1. display `posted on`/`updated on` dates
2. list nested subject areas (2-levels) including a link to sub-category 
3. Investigate adding the average review score and number of reviews under the book cover
4. Remove "Need help" link, but keep Original source and adaptations links. (not reflected in wireframe) 
5. Rename and move adoptions link to "Tell us you're using this Open Textbook" 
6. Unlike wireframe, do not add/implement the button for "read this book" as it's redundant
7. Ensure correct attribution to cover image is displayed (missing from wireframes) 
8. Ensure sidebar is included (missing from wireframes)

TBD: Logic behind the removal of the sidebar menu, and look at addition of breadcrumbs 

![bookdetails](https://user-images.githubusercontent.com/43043264/53135041-7dfcd480-352e-11e9-85e4-e08bb31ba045.png)

**Comment by ehbeattie** [comment]
Really great work on this one!
