### ISSUE TITLE
Homepage: Stats section

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#8]
Static content, as per design. @murphybarb waiting on SVG images and text.

**Comment by murphybarb** [comment]
SVG files are in the assets folder: 
https://cloud.bccampus.ca/index.php/s/xwse8RW9yYxMyHr

**Comment by bdolor** [comment]
Erin will provide copy. 
Note: Student Savings is to be a range as is the case on the existing site.

**Comment by bdolor** [comment]
![image](https://user-images.githubusercontent.com/2048170/51857621-925f0000-22e7-11e9-9b6c-fdb7264cbeab.png)

**Comment by alex-418** [comment]
@ehbeattie to provide content

**Comment by ehbeattie** [comment]
Content: The high cost of educational resources and textbooks creates a serious obstacle to the access of post-secondary education

**Comment by ehbeattie** [comment]
Back to you @alex-418

**Comment by ehbeattie** [comment]
Looks great!
