### ISSUE TITLE
[75.3] Investigate the use stars instead of bars, align to the right

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#81]

**Comment by bdolor** [comment]
The meter element is rendered by the browser which makes it unique. Telling the browser to display it in a star format is not possible.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

**Comment by ehbeattie** [comment]
Fair enough.

**Comment by ehbeattie** [comment]
⭐for effort
