### ISSUE TITLE
[75.5] Move "Review this book" link below Reviews heading. Rename to "Request to review this textbook"

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#83]

**Comment by ehbeattie** [comment]
I'm not seeing this title/heading... where should I be looking? 

I'm looking here --> https://helga.bccampus.ca/wp/opentextbooks/find-open-textbooks/?uuid=f4873e49-e09c-469e-9ee8-9f14ca5a4e00&contributor=&keyword=&subject=

**Comment by bdolor** [comment]
https://helga.bccampus.ca/wp/opentextbooks/find-open-textbooks/?uuid=fdb68dba-0709-4778-a2f7-af8bafd84fa9&contributor=&keyword=&subject=Hospitality/Tourism%20-%20General
