### ISSUE TITLE
[76.1] Similar textbooks component structure and styling

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#84]
Data should come from https://github.com/BCcampus/opentextbooks/issues/123 Return 4 similar textbooks (from a relevant area) when viewing an individual textbook page

**Comment by bdolor** [comment]
can be validated on any individual resource page https://helga.bccampus.ca/wp/opentextbooks/find-open-textbooks/?uuid=a3f11842-79a9-45cf-8039-8b8f0263257b&contributor=&keyword=&subject=

**Comment by ehbeattie** [comment]
Looks awesome!
