### ISSUE TITLE
[68.1] Get current WCAG 2.0 rating of website

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#88]

**Comment by alex-418** [comment]
Confirmed via a web accessibility tool that we meet AA standards. There's a few issues that can be easily fixed in some pages: 

![Ratings](https://user-images.githubusercontent.com/17072191/54569926-dd1d0000-4999-11e9-8581-6fc677080056.png)

**Comment by ehbeattie** [comment]
I'll have to trust you on this one.
