### ISSUE TITLE
Homepage: "The high cost of education" box under stats

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#9]
Static content, as per design (halfsies). The right side is a menu the user can control. Possibly no Carrots/Chevrons on menu items. @murphybarb to confirm.

**Comment by bdolor** [comment]
no chevrons

**Comment by bdolor** [comment]
![image](https://user-images.githubusercontent.com/2048170/51857700-c5a18f00-22e7-11e9-91d9-82900a8e1915.png)

**Comment by alex-418** [comment]
Not needed.
