### ISSUE TITLE
[69.1] Style updates to stats page

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#90]
Implement new styling as per design where possible.

**Comment by alex-418** [comment]
Just documenting that this requires the following plugin and short-code to be added to the open stats page: `[includeme file=wp-content/opensolr/opentextbooks/reports.php]` I will tackle that on cert if it isn't already set up that way.

**Comment by bdolor** [comment]
would like to suggest an alternate method for integration. Will point to examples in RC.

**Comment by alex-418** [comment]
![exc](https://user-images.githubusercontent.com/17072191/53530178-e8b88d80-3aa3-11e9-8ef4-56407da84a0b.gif)

**Comment by bdolor** [comment]
can be validated at https://helga.bccampus.ca/wp/opentextbooks/open-textbook-stats/

**Comment by ehbeattie** [comment]
This looks lovely and I assume the right nav will all come into play once we establish the parent/child relationships. Would it make sure to pull Josie and/or Lauri in to give this one the final nod?

**Comment by bdolor** [comment]
I believe as product owner, that you are the final nod (though your nod should represent stakeholder interests)

**Comment by ehbeattie** [comment]
Being that you're updating styling on this and not modifying the actual stats, I feel like I can sign off on this one. My trust bucket is full. 👍
