### ISSUE TITLE
[62.2] Use open textbooks "Guides and Toolkits" component

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#93]
Page 7 in open.Bccampus.ca template markup

**Comment by alex-418** [comment]
![screen shot 2019-02-22 at 2 33 11 pm](https://user-images.githubusercontent.com/17072191/53275164-e246a200-36ae-11e9-92bc-04594640d7c7.png)

**Comment by alex-418** [comment]
@ehbeattie to provide content (guides and links)

**Comment by alex-418** [comment]
Content appears to have been provided in https://github.com/BCcampus/open-sage/issues/26#issuecomment-458273166 and this part was left as user editable (you can use the WYSIWYG of the page to create this). Please confirm this does not need further development work.

**Comment by alex-418** [comment]
Identified at the stand up meeting today that this is going to be static content. @josieg to provide content.

**Comment by josieg** [comment]
**Faculty open educational resources (OER) toolkits**
Refer to these useful guides to learn more about self-publishing, adopting, and adapting open textbooks and other OER.

- Self-Publishing Guide (https://opentextbc.ca/selfpublishguide/)
- Adaption Guide (https://opentextbc.ca/adaptopentextbook/)
- Adoption Guide (https://opentextbc.ca/adoptopentextbook/)

**Comment by alex-418** [comment]
That was fast, thanks @josieg

**Comment by alex-418** [comment]
Completed via #96 

![screenshot](https://user-images.githubusercontent.com/17072191/53441972-f3e4be00-39bc-11e9-9e8c-e8b4bd98555a.png)

**Comment by josieg** [comment]
Hi @alex-418 ! This is totally my fault - but the second guide should be spelt "Adaptation Guide." Sorry about that.

**Comment by alex-418** [comment]
Thanks @josieg that change should be reflected soon on cert, resolved via https://github.com/BCcampus/open-sage/commit/093a5ca03ad543f5e2618e90e3c5b9df8d955867

**Comment by josieg** [comment]
Perfect. Consider this issue "validated." Will wait for Erin's final approval.

**Comment by ehbeattie** [comment]
Will there be a thumbnail image as per the design?

**Comment by alex-418** [comment]
@ehbeattie sure there could be... but the designs thumbnail image was for a single resource only. And right now we have the three guides instead, so I i'm not sure which thumbnail image would work well for all of those three? Let me know and I could add it.

**Comment by ehbeattie** [comment]
Ah, you make a solid point. Good to go!
