### ISSUE TITLE
[62.3] Create open Textbooks "Guides and Toolkits" component

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#94]
Page 8 in open.Bccampus.ca template markup (located in two places on this page.)

**Comment by alex-418** [comment]
![screen shot 2019-02-22 at 2 31 23 pm](https://user-images.githubusercontent.com/17072191/53275151-d5c24980-36ae-11e9-9736-ef5ba0430a44.png)

**Comment by alex-418** [comment]
@ehbeattie to provide content (guides and links)

**Comment by bdolor** [comment]
duplicate of https://github.com/BCcampus/open-sage/issues/114
